name: Linting
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Checking formatting
        run: npm run format
      